export const REGISTRATION_FORM_DATA = 'REGISTRATION_FORM_DATA';
export const REGISTRATION_UPDATE_FORM = 'REGISTRATION_UPDATE_FORM';

export const REGISTRATION_OS_TEMPLATE = 'REGISTRATION_OS_TEMPLATE';
export const REGISTRATION_COMMAND = 'REGISTRATION_COMMAND';
