export const CHANGE_CONTENT_SOURCE_DATA = 'CHANGE_CONTENT_SOURCE_DATA';
export const CHANGE_CONTENT_SOURCE_CAPSULE = 'CHANGE_CONTENT_SOURCE_CAPSULE';
export const CHANGE_CONTENT_SOURCE = 'CHANGE_CONTENT_SOURCE';
export const CHANGE_CONTENT_SOURCE_VIEWS = 'CHANGE_CONTENT_SOURCE_VIEWS';
